### ISSUE TITLE
Mid-Word Text Wrapping in Links

### ISSUE THREAD

**Issue by Foggalong** [QuidditchUK/chaser#210]
**Describe the bug**
When the link text is sufficiently long that it needs to wrap it wrap mid-word rather than at spaces.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a page with long link text 
2. Reduce window width until link's cut

**Expected behavior**
It wraps at the spaces between words.

**Screenshots**
![Screenshot from 2021-10-06 19-17-06](https://user-images.githubusercontent.com/5920259/136260699-74633a77-6b93-4c81-98c1-7f10b299698d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 92.0

**Additional context**
Came across this when drafting an article in preview mode, will confirm it appears as well when published.

**Comment by Foggalong** [comment]
Can confirm on live article too, see [this post](https://quidditchuk.org/news/quks-september-2021-update).

![Screenshot from 2021-10-06 20-19-26](https://user-images.githubusercontent.com/5920259/136268964-8654ab04-0b9d-4dd1-bb6c-d7731e3142bb.png)

**Comment by declanramsay** [comment]
Resolved some time ago :)
