### ISSUE TITLE
Lost Table Text Formatting

### ISSUE THREAD

**Issue by Foggalong** [QuidditchUK/chaser#267]
**Describe the bug**
Text formatting and newlines are lost in the two column table widget.

**To Reproduce**
1. Create a page which uses the two-column table widget
2. Use formatting or newlines in that table's contents.

**Expected behavior**
Text formatting appears in rendered webpage.

**Screenshots**
![Screenshot from 2022-07-29 17-53-05](https://user-images.githubusercontent.com/5920259/181807745-76f7ba82-33c6-47c0-8bc8-d8f1af9c78b5.png)
![Screenshot from 2022-07-29 17-52-58](https://user-images.githubusercontent.com/5920259/181807748-f3aaffa3-ebf4-4fb6-9e74-a63f1ccec891.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Like 103

**Comment by declanramsay** [comment]
Resolved!
