### ISSUE TITLE
Big Profile

### ISSUE THREAD

**Issue by Foggalong** [QuidditchUK/chaser#273]
**Describe the bug**
Profile button has become very oversized.

**To Reproduce**
1. Open a page which has the profile button.

**Expected behavior**
Profile button about the same size as the notification button.

**Screenshots**
![Screenshot from 2022-08-30 18-35-02](https://user-images.githubusercontent.com/5920259/187505676-9593f156-8acd-4e5a-b9bd-5164b419fa3d.png)
![Screenshot from 2022-08-30 18-34-47](https://user-images.githubusercontent.com/5920259/187505684-4a8af4bc-8f34-4dc8-b5c4-5f6dd7636eb0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 104

**Comment by Foggalong** [comment]
The size also seems to vary between refreshes

![Screenshot from 2022-08-30 19-25-04](https://user-images.githubusercontent.com/5920259/187514328-7050ac8b-438b-4708-9e80-60f0517fc2ed.png)

**Comment by declanramsay** [comment]
Thanks for the report, was affecting Firefox only, fix is now out and looking fine 👍

**Comment by Foggalong** [comment]
No problemo! Out of curiosity what caused it? I've never seen an element resizing seemingly at random between refreshes before
